### ISSUE TITLE
Release action to the marketplace (v1)

### ISSUE THREAD

**Issue by rickstaa** [reviewdog/action-remark-lint#11]
To release the action to the marketplace the following todos have to be completed:

- [x] Merge #8.
- [x] Create v1 release.
- [x] Accept organization marketplace terms of service.

**Comment by rickstaa** [comment]
🚀 The first stable version of this action has been released. @haya14busa, @prologic, @asbjornu thanks a lot for making this in my opinion very helpful action possible.

**Comment by haya14busa** [comment]
:+1::100:
