### ISSUE TITLE
npm install required?

### ISSUE THREAD

**Issue by asbjornu** [reviewdog/action-remark-lint#41]
Unless I do `run: npm install` in a step before running `reviewdog/action-remark-lint@v2`, I get warnings about missing plugins. I feel that `npm install` is something the action should do itself, no?

**Comment by rickstaa** [comment]
@asbjornu You'r correct. We should apply similar steps like (https://github.com/reviewdog/action-eslint/blob/master/script.sh) and (https://github.com/reviewdog/action-coffeelint/blob/master/entrypoint.sh).

**Comment by rickstaa** [comment]
@asbjornu I just run another test, but in my case everything works fine (see [here](https://github.com/rickstaa/action-test-repo/runs/3136407827?check_suite_focus=true)). Can you maybe give me more information on how to reproduce the warning or show the action where you received the warning? 

I also checked the [base Dockerfile](https://hub.docker.com/r/prologic/remark-lint/tags?page=1&ordering=last_updated) (by using the `docker history` command, as the repository it is not public) and it looks like remark is installed as a global npm package. I therefore would expect everything to work fine.

**Comment by rickstaa** [comment]
Maybe @prologic still has access to the `prologic/remark-lint:latest` and can share the original Dockerfile, so we can double-check what goes on.

**Comment by rickstaa** [comment]
@asbjornu Can you maybe also check the `remark-cli` that is installed in the action where you got the warning. It might be that in that version a dependency (plugin) was missing in the `package.json` but in the new version this is solved.

**Comment by asbjornu** [comment]
I don't have a repro available, but your test repo does not seem to have any Remark plugins. It's the plugins that fail loading, not Remark itself.

**Comment by rickstaa** [comment]
@asbjornu Good point, I missed the fact that you used plugins. I will run some new tests.

**Comment by rickstaa** [comment]
@asbjornu I reproduced [your issue,](https://github.com/rickstaa/action-test-repo/pull/58) I will write a fix now. I will send it to you for review later today.

**Comment by rickstaa** [comment]
@asbjornu I created a pull request in #43. Please review it and merge it if you think it is correct.
