### ISSUE TITLE
`github_token` should be made an optional property

### ISSUE THREAD

**Issue by asbjornu** [reviewdog/action-remark-lint#60]
Since `github_token` is set to `github.token` by default, its `required` property can be set to `false`.

https://github.com/reviewdog/action-remark-lint/blob/aa064e1d6f09a7b7b11b18f7f4e287780589c362/action.yml#L20-L23

**Comment by rickstaa** [comment]
Looks good to me. For future reference see https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret)
