### ISSUE TITLE
Transfer repository to the reviewdog repository

### ISSUE THREAD

**Issue by rickstaa** [reviewdog/action-remark-lint#7]
I think it might be a good idea to transfer the action to the [reviewdog organization](https://github.com/reviewdog/). In this way, the whole team can help to maintain it. @prologic Let me know what you think so we can organize the transfer.

**Comment by prologic** [comment]
Sounds good to me. Just say the word and I'll hit the button.

**Comment by rickstaa** [comment]
Amazing! :rocket: I will open a issue on the reviewdog repo to give you transfer rights. In the meantime maybe you can merge #6 and create a v1 release.

**Comment by rickstaa** [comment]
The issue can be followed on https://github.com/reviewdog/reviewdog/issues/836.

**Comment by rickstaa** [comment]
MAybe it is better to do the v1 release under the organization. I just saw the badges also need updating when it is transfered.

**Comment by rickstaa** [comment]
I created a pull request to fix the badges #8. The only thing left to do is for @haya14busa or any of the other admins to accept the GitHub marketplace terms and release the action under v1.0.

**Comment by haya14busa** [comment]
I couldn't find any GitHub marketplace terms link, do we need to accept the term in every repo?

Anyway, I changed prologic's role to admin of this repo, so can you try releasing v1 and let me know if you couldn't release it to the marketplace.

**Comment by rickstaa** [comment]
@haya14busa I noticed that as well when I transferred the [https://github.com/reviewdog/action-black](https://github.com/reviewdog/action-black) Github Action. I am unsure what went wrong when I transferred the action-flake8. Maybe because it was a fork.
